version: "3"

services:
  #PHP
    app:
        build: .
        container_name: app
        entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - REDIS_HOST=redis
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
           - db
           - redis
  #WEBSERVER
    nginx:
        build: .docker/nginx
        container_name: nginx
        entrypoint: dockerize -template /var/www/.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g 'daemon off;'
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        environment:
            - PHP_HOST=app
            - PHP_PORT=9000
        depends_on:
            - app
  #DATABASE
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network
  #CACHE
    redis:
        image: redis:alpine
        expose:
            - "6379"
        networks:
            - app-network

#NETWORKS
networks:
    app-network:
        driver: bridge
